# Generated by Django 5.2 on 2025-04-22 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WantMusic_infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_tag', to='WantMusic_infraestructura.contenido')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TagWant_infraestructura.etiqueta')),
            ],
            options={
                'unique_together': {('contenido', 'etiqueta')},
            },
        ),
    ]
