# Generated by Django 5.2.1 on 2025-05-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TagWant', '0001_initial'),
        ('WantMusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoetiqueta',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_etiquetas', to='WantMusic.contenido'),
        ),
        migrations.AddField(
            model_name='contenidoetiqueta',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_etiquetas', to='TagWant.etiqueta'),
        ),
        migrations.AlterUniqueTogether(
            name='contenidoetiqueta',
            unique_together={('contenido', 'etiqueta')},
        ),
    ]
