# Generated by Django 5.2 on 2025-04-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('gustos_musicales', models.TextField(blank=True, null=True)),
                ('historial_reproducciones', models.TextField(blank=True, null=True)),
                ('favoritos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('etiquetas', models.TextField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_subidos', to='WantMusic_infraestructura.usuario')),
            ],
        ),
    ]
