# Generated by Django 5.2.1 on 2025-05-30 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagWant', '0002_initial'),
        ('WantMusic', '0002_contenido_eliminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEtiquetaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_que_la_prefieren', to='TagWant.etiqueta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'etiqueta')},
            },
        ),
    ]
