# Generated by Django 5.2.1 on 2025-05-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WantAdministrator', '0001_initial'),
        ('WantMusic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoeliminado',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WantMusic.contenido'),
        ),
    ]
